### ISSUE TITLE
TypeError: (0 , s.promisify) is not a function

### ISSUE THREAD

**Issue by dafe123** [atom-ide-community/minimap-plus#21]
Hello,

I got the following error message after updating atom: 
TypeError: (0 , s.promisify) is not a function

I tried to reinstall minimap-plus, but the error appears again

**Comment by aminya** [comment]
Please install minimap directly. minimap-plus is deprecated

**Comment by dafe123** [comment]
Thank you for your fast answer. After reinstalling atom and installing minimap instead of minimap-plus ervrythink works fine
